version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis:redis
