version: '2'
services:
  redis:
    ports:
     - "0.0.0.0:6379:6379"
    image: redis:latest
    restart: always

  web:
    restart: always
    build: .
    volumes:
      - .:/code
    command: python3 ./ba_server/bid_ask_server/manage.py runserver 0.0.0.0:8000
    environment:
      - REDIS_HOST=redis
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - redis
    links:
      - redis:redis
